### ISSUE TITLE
Dump requests group link is broken

### ISSUE THREAD

**Issue by jkmartindale** [AndroidDumps/dumpyara#12]
The README links to https://t.me/dumprequests, which is a blank channel parking the username

**Comment by ghost** [comment]
A collection of dumps of various Android stock ROMs. 

https://dumps.tadiphone.dev/dumps

For the requests, see here:
https://t.me/joinchat/SjCNPhqgXVEGXJqI

**Comment by jkmartindale** [comment]
Channel has been updated appropriately
