### ISSUE TITLE
Couldn't extract system partition by 7z. Using fsck.erofs

### ISSUE THREAD

**Issue by nguyenhung9xdev2022** [AndroidDumps/dumpyara#39]
I try extract firmware samsung galaxy A73 but it get problem. How to fix

Couldn't extract system partition by 7z. Using fsck.erofs.
<E> erofs: cannot find valid erofs superblock
<E> erofs: failed to read superblock
Couldn't extract system partition by fsck.erofs. Using mount loop

**Comment by nguyenhung9xdev2022** [comment]
![image](https://user-images.githubusercontent.com/101638735/196029070-f5d26268-c25e-4810-8a32-00c8e6bd7759.png)

**Comment by deadman96385** [comment]
You are using a different repo, report it there

https://github.com/AndroidHQ254/DumprX

**Comment by nguyenhung9xdev2022** [comment]
All two script Dumpyara with DumprX same problem!!!. A73 uses ext4 not erofs
