### ISSUE TITLE
Same problem

### ISSUE THREAD

**Issue by nguyenhung9xdev2022** [AndroidDumps/dumpyara#40]
You are using a different repo, report it there

https://github.com/AndroidHQ254/DumprX

_Originally posted by @deadman96385 in https://github.com/AndroidDumps/dumpyara/issues/39#issuecomment-1279974490_

All two script Dumpyara with DumprX same problem!!!. A73 uses ext4 not erofs

**Comment by deadman96385** [comment]
You need to run the script with sudo

**Comment by nguyenhung9xdev2022** [comment]
> You need to run the script with sudo
How to fix WARNING: source write-protected, mounted read-only
![image](https://user-images.githubusercontent.com/101638735/196069610-00a5699c-9fdb-4427-a176-51320898852b.png)
![image](https://user-images.githubusercontent.com/101638735/196069722-7fac72af-051a-4b86-9be2-e157937c28bd.png)

**Comment by deadman96385** [comment]
Can you provide a link to this firmware? I can then debug why it's happening. We haven't seen that error before.

**Comment by nguyenhung9xdev2022** [comment]
> Can you provide a link to this firmware? I can then debug why it's happening. We haven't seen that error before.

https://samfw.com/firmware/SM-A736B/XXV/A736BXXU2AVG3

**Comment by ghost** [comment]
This happens on basically all Samsung devices with EROFS as partition. Tried with [SM-A137F](https://samfw.com/firmware/SM-A137F/EUX/A137FXXS1AVJ1) too.
