### ISSUE TITLE
Telegram channel unavailable https://t.me/dumprequests

### ISSUE THREAD

**Issue by P-D-A** [AndroidDumps/dumpyara#43]
Greetings
Where can I send a request?
Thanks

**OnePlus 10 Pro** (op516fl1)
[India(IN) (NE2211_11.C.22)](https://gauss-componentotacostmanual-sg.allawnofs.com/remove-395fb562c95aa02fc42d439d400d6893/component-ota/22/11/25/fc76d5c19179495399b5a8c3a1c23ad9.zip)

[Europe(EU) (NE2213_11_C.22)](https://gauss-componentotacostmanual-sg.allawnofs.com/remove-909e235f94f7caba34d4eb1efa4616aa/component-ota/22/11/25/3e49e275c73448eeb3635f5cf58ae3d5.zip)

[Global(GLO) (NE2213_11_C.22)](https://gauss-componentotacostmanual-sg.allawnofs.com/remove-42e513ffb75cc52a44009bbcee72bbf6/component-ota/22/11/25/d5ff23243cdf4bc3a0ac313975792c2d.zip)

[North America(NA) (NE2215_11.C.22)](https://android.googleapis.com/packages/ota-api/package/ab213fafecc048df784fe4992fc6023f2122d117.zip)

**Comment by kacskrz** [comment]
[Here](https://t.me/CalsiBot?start=preverify----1001244695870---guxes3o0q5mi6jozhw8g7g4iikejca)
