### ISSUE TITLE
No system/vendor/product build*.prop found, pushing cancelled.

### ISSUE THREAD

**Issue by naden01** [AndroidDumps/dumpyara#64]
No system/vendor/product build*.prop found, pushing cancelled.
 
how to fix it?

**Comment by richardqcarvalho** [comment]
It probably means you have a splitted super image inside file you're using or directory you're selecting. I suggest you to extract file (if you're using one), use ```simg2img``` to merge all super image parts in one and use ```lpunpack``` to extract all images inside it. Then having all these images, dumpyara will use it properly without this problem you had.

**Comment by naden01** [comment]
ok i will try it
